services:
  db:
    image: postgres:15-alpine
    container_name: inventory-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: inventory_db
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
